### ISSUE TITLE
invalid key

### ISSUE THREAD

**Issue by mchomvu** [Aetherinox/ScreenpressoKeygen#1]
Invalid key after internet connection

**Comment by Aetherinox** [comment]
Did you click the top button to block screenpresso's servers? The Block host button will add a series of entries to your OS host file which should keep it from deactivating.

I Just checked the list and it appears to be up to date.

**Comment by Aetherinox** [comment]
I just checked the current install and it did add the host blocks fine on my end
```
# Screenpresso Host Block
0.0.0.0 screenpresso.com
0.0.0.0 www.screenpresso.com
0.0.0.0 secure.screenpresso.com
0.0.0.0 stats.screenpresso.com
0.0.0.0 18.65.3.28
```

I'm going to load up the program on another machine along with a network tracker, and see if a new IP address or host has been added.

**Comment by Aetherinox** [comment]
So, mine continued to stay activated. However, I did notice one IP address / DNS that hasn't been seen before is now communicating between the software and Screenpresso's servers; so I'm going to block.

**Comment by Aetherinox** [comment]
Added the new entry. I will be loading up the program on a fresh machine to do a full run-through to make sure everything works, and then I'll push a release.

**Comment by Aetherinox** [comment]
Yeah, I can confirm, if your internet is somehow able to communicate with the Screenpresso servers, the software will return an invalid license.
As soon as you block the addresses again and restart Screenpresso, the software works fine and stays activated.
So you just need to make sure the entries are actually getting added to the hosts file I mentioned above.

**Comment by mchomvu** [comment]
jus use netlimiter and its working fine thanks

**Comment by Aetherinox** [comment]
I'm actually modifying the code right now so that in the next update, it's going to auto-add two rules to the Windows firewall for inbound and outbound. That should ensure it doesn't get past the filters, just as a backup to the windows host files.

**Comment by Aetherinox** [comment]
Pretty much solves the issue for anyone who gets the same thing you had. Either the hosts file will do it, or WIndows Firewall will be the backup.

![8T31Req](https://github.com/Aetherinox/ScreenpressoKeygen/assets/118329232/86b29291-b090-42a8-a41d-4d8231c28371)

**Comment by Aetherinox** [comment]
Pushed out an update. If you have issues in the future, let me know.

**Comment by mchomvu** [comment]
Thanks, keep it up
  

  

  

  
  
  
  
  
>

**Comment by mchomvu** [comment]
👍
  

  

  

  
  
  
  
  
>
